import { MigrationInterface, QueryRunner } from 'typeorm';
export class SpecialTestsPermissions1788573600000 implements MigrationInterface {
  name = 'SpecialTestsPermissions1788573600000';
  async up(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query(`INSERT INTO security_permissions (code,name,description,module,is_active) VALUES ('special-tests.read','Consultar pruebas especiales','Permite consultar laboratorios de pruebas especiales','special-tests',1),('special-tests.create','Crear pruebas especiales','Permite crear laboratorios de pruebas especiales','special-tests',1),('special-tests.update','Actualizar pruebas especiales','Permite editar laboratorios de pruebas especiales','special-tests',1),('special-tests.change-status','Cambiar estado de pruebas especiales','Permite activar o inactivar laboratorios de pruebas especiales','special-tests',1),('special-test-items.read','Consultar items de pruebas especiales','Permite consultar items asociados a pruebas especiales','special-tests',1),('special-test-items.create','Crear items de pruebas especiales','Permite asociar examenes a pruebas especiales','special-tests',1),('special-test-items.update','Actualizar items de pruebas especiales','Permite editar items asociados a pruebas especiales','special-tests',1),('special-test-items.delete','Eliminar items de pruebas especiales','Permite eliminar asociaciones de pruebas especiales','special-tests',1) ON DUPLICATE KEY UPDATE name=VALUES(name),description=VALUES(description),module=VALUES(module),is_active=1`);
    await queryRunner.query(`INSERT IGNORE INTO security_role_permissions (role_id,permission_id) SELECT role.id,permission.id FROM security_roles role CROSS JOIN security_permissions permission WHERE role.code='admin' AND role.is_active=1 AND permission.code IN ('special-tests.read','special-tests.create','special-tests.update','special-tests.change-status','special-test-items.read','special-test-items.create','special-test-items.update','special-test-items.delete')`);
  }
  async down(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query(`DELETE assignment FROM security_role_permissions assignment INNER JOIN security_permissions permission ON permission.id=assignment.permission_id WHERE permission.code IN ('special-tests.read','special-tests.create','special-tests.update','special-tests.change-status','special-test-items.read','special-test-items.create','special-test-items.update','special-test-items.delete')`);
    await queryRunner.query(`DELETE FROM security_permissions WHERE code IN ('special-tests.read','special-tests.create','special-tests.update','special-tests.change-status','special-test-items.read','special-test-items.create','special-test-items.update','special-test-items.delete')`);
  }
}
