import { BadRequestException,ConflictException,Injectable,NotFoundException,Optional } from '@nestjs/common';
import { InjectRepository } from '@nestjs/typeorm';
import { DataSource,EntityManager,Repository } from 'typeorm';
import { SecurityAuditService } from '../audit/security-audit.service';
import { ChangeCurrencyStatusDto } from './dto/change-currency-status.dto';
import { CreateCurrencyDto } from './dto/create-currency.dto';
import { UpdateCurrencyDto } from './dto/update-currency.dto';
import { Currency } from './currency.entity';
import { PaymentMethodCurrency } from './payment-method-currency.entity';
@Injectable()
export class CurrencyService {
  constructor(@InjectRepository(Currency)private readonly repository:Repository<Currency>,@InjectRepository(PaymentMethodCurrency)private readonly assignments:Repository<PaymentMethodCurrency>,@Optional()private readonly dataSource?:DataSource,@Optional()private readonly audit?:SecurityAuditService){}
  getAll(){return this.repository.find({order:{displayOrder:'ASC',name:'ASC',id:'ASC'}});}
  getActive(){return this.repository.find({where:{isActive:true},order:{displayOrder:'ASC',name:'ASC',id:'ASC'}});}
  async getOne(id:number){this.id(id);const row=await this.repository.findOne({where:{id}});if(!row)throw new NotFoundException('CURRENCY_NOT_FOUND');return row;}
  async create(body:CreateCurrencyDto,actorUserId?:number){const values=this.normalizeCreate(body);return this.write(actorUserId,async manager=>{const repository=manager.getRepository(Currency);await this.unique(repository,values.code,values.name);const displayOrder=await this.nextOrder(repository);const saved=await repository.save(repository.create({...values,isBase:false,isLocal:false,isActive:true,displayOrder}));await this.writeAudit(manager,Number(actorUserId),'currency.created',saved,{code:saved.code,name:saved.name});return saved;});}
  async update(id:number,body:UpdateCurrencyDto,actorUserId?:number){this.id(id);const values=this.normalizeUpdate(body);return this.write(actorUserId,async manager=>{const repository=manager.getRepository(Currency);const row=await repository.createQueryBuilder('currency').setLock('pessimistic_write').where('currency.id=:id',{id}).getOne();if(!row)throw new NotFoundException('CURRENCY_NOT_FOUND');await this.unique(repository,row.code,values.name??row.name,id);const previous={name:row.name,symbol:row.symbol,symbolPosition:row.symbolPosition,decimalPlaces:row.decimalPlaces};Object.assign(row,values);const saved=await repository.save(row);await this.writeAudit(manager,Number(actorUserId),'currency.updated',saved,{previous,current:values});return saved;});}
  async changeStatus(id:number,body:ChangeCurrencyStatusDto,actorUserId?:number){this.id(id);if(!body||typeof body!=='object'||typeof body.isActive!=='boolean')throw new BadRequestException('CURRENCY_STATUS_INVALID');return this.write(actorUserId,async manager=>{const repository=manager.getRepository(Currency);const row=await repository.createQueryBuilder('currency').setLock('pessimistic_write').where('currency.id=:id',{id}).getOne();if(!row)throw new NotFoundException('CURRENCY_NOT_FOUND');if(row.isActive===body.isActive)return row;if(!body.isActive){if(row.isBase)throw new ConflictException('CURRENCY_BASE_CANNOT_BE_DEACTIVATED');if(row.isLocal)throw new ConflictException('CURRENCY_LOCAL_CANNOT_BE_DEACTIVATED');if(await repository.count({where:{isActive:true}})<=1)throw new ConflictException('CURRENCY_LAST_ACTIVE_CANNOT_BE_DEACTIVATED');const assigned=await manager.getRepository(PaymentMethodCurrency).count({where:{currencyId:id,isActive:true}});if(assigned>0)throw new ConflictException('CURRENCY_IN_USE');}row.isActive=body.isActive;const saved=await repository.save(row);await this.writeAudit(manager,Number(actorUserId),body.isActive?'currency.activated':'currency.deactivated',saved,{isActive:body.isActive});return saved;});}
  private normalizeCreate(body:CreateCurrencyDto){if(!body||typeof body!=='object'||Array.isArray(body))throw new BadRequestException('CURRENCY_BODY_REQUIRED');return{code:this.code(body.code),name:this.name(body.name),symbol:this.symbol(body.symbol),symbolPosition:this.position(body.symbolPosition),decimalPlaces:this.decimals(body.decimalPlaces)};}
  private normalizeUpdate(body:UpdateCurrencyDto){if(!body||typeof body!=='object'||Array.isArray(body)||Object.keys(body).length===0)throw new BadRequestException('CURRENCY_UPDATE_REQUIRED');const allowed=['name','symbol','symbolPosition','decimalPlaces'];if(Object.keys(body).some(field=>!allowed.includes(field)))throw new BadRequestException('CURRENCY_FIELD_UNKNOWN');const values:Partial<Currency>={};if(Object.prototype.hasOwnProperty.call(body,'name'))values.name=this.name(body.name);if(Object.prototype.hasOwnProperty.call(body,'symbol'))values.symbol=this.symbol(body.symbol);if(Object.prototype.hasOwnProperty.call(body,'symbolPosition'))values.symbolPosition=this.position(body.symbolPosition);if(Object.prototype.hasOwnProperty.call(body,'decimalPlaces'))values.decimalPlaces=this.decimals(body.decimalPlaces);return values;}
  private code(value:unknown){if(typeof value!=='string'||!/^[A-Z]{3}$/.test(value.trim().toUpperCase()))throw new BadRequestException('CURRENCY_CODE_INVALID');return value.trim().toUpperCase();}
  private name(value:unknown){if(typeof value!=='string'||value.trim()===''||value.trim().length>80)throw new BadRequestException('CURRENCY_NAME_INVALID');return value.trim();}
  private symbol(value:unknown){if(typeof value!=='string'||value.trim()===''||value.trim().length>12)throw new BadRequestException('CURRENCY_SYMBOL_INVALID');return value.trim();}
  private position(value:unknown):'before'|'after'{if(value!=='before'&&value!=='after')throw new BadRequestException('CURRENCY_SYMBOL_POSITION_INVALID');return value;}
  private decimals(value:unknown){const number=Number(value);if(!Number.isInteger(number)||number<0||number>6)throw new BadRequestException('CURRENCY_DECIMAL_PLACES_INVALID');return number;}
  private id(value:number){if(!Number.isInteger(value)||value<=0)throw new BadRequestException('CURRENCY_ID_INVALID');}
  private async unique(repository:Repository<Currency>,code:string,name:string,excludedId?:number){const rows=await repository.find({select:{id:true,code:true,name:true}});if(rows.some(row=>row.id!==excludedId&&row.code.toUpperCase()===code.toUpperCase()))throw new ConflictException('CURRENCY_CODE_ALREADY_EXISTS');if(rows.some(row=>row.id!==excludedId&&row.name.trim().toLowerCase()===name.trim().toLowerCase()))throw new ConflictException('CURRENCY_NAME_ALREADY_EXISTS');}
  private async nextOrder(repository:Repository<Currency>){const row=await repository.createQueryBuilder('currency').select('COALESCE(MAX(currency.displayOrder),0)','value').getRawOne<{value:number|string}>();return Number(row?.value??0)+1;}
  private async write<T>(actorUserId:number|undefined,action:(manager:EntityManager)=>Promise<T>){if(!Number.isInteger(actorUserId)||Number(actorUserId)<=0)throw new BadRequestException('CURRENCY_ACTOR_REQUIRED');if(!this.dataSource)throw new Error('CURRENCY_TRANSACTION_UNAVAILABLE');return this.dataSource.transaction(action);}
  private async writeAudit(manager:EntityManager,actorUserId:number,action:string,row:Currency,metadata:Record<string,unknown>){if(!this.audit)throw new Error('SECURITY_AUDIT_SERVICE_UNAVAILABLE');await this.audit.write(manager,{actorUserId,action,entityType:'currency',entityId:row.id,summary:action==='currency.created'?'Moneda creada':action==='currency.activated'?'Moneda activada':action==='currency.deactivated'?'Moneda inactivada':'Moneda actualizada',metadata});}
}
