import { BadRequestException, Injectable, NotFoundException, Optional } from '@nestjs/common';
import { InjectRepository } from '@nestjs/typeorm';
import { DataSource, EntityManager, In, Not, Repository } from 'typeorm';
import { SecurityAuditService } from '../audit/security-audit.service';
import { CreateTypepaymantDto } from './dto/create-typepayment.dto';
import { UpdateTypepaymantDto } from './dto/update-typepayment.dto';
import { Currency } from './currency.entity';
import { PaymentMethodCurrency } from './payment-method-currency.entity';
import { PaymentMethodField, PaymentFieldType } from './payment-method-field.entity';
import { PaymentMethodFieldInputDto } from './dto/payment-method-field-input.dto';
import { TypePayment } from './typepayment.entity';

@Injectable()
export class TypePaymentService {
  constructor(@InjectRepository(TypePayment) private readonly repository: Repository<TypePayment>, @Optional() private readonly dataSource?: DataSource, @Optional() private readonly audit?: SecurityAuditService) {}
  getTypepayments() { return this.repository.find({ relations: { currencies: { currency: true }, fields: true }, order: { displayOrder: 'ASC', description: 'ASC' } }); }
  async getTypepayment(id: number) { this.validateId(id); const record=await this.repository.findOne({ where:{id}, relations:{currencies:{currency:true},fields:true} }); if(!record)throw new NotFoundException('TYPEPAYMENT_NOT_FOUND'); return record; }
  async createTypepayment(body: CreateTypepaymantDto, actorUserId?: number) { const input=this.normalizeCreate(body); if(actorUserId===undefined)return this.createWithManager(this.repository.manager,input); if(!this.dataSource)throw new Error('TYPEPAYMENT_TRANSACTION_UNAVAILABLE'); return this.dataSource.transaction((manager)=>this.createWithManager(manager,input,actorUserId)); }
  async updateTypepayment(id:number, body:UpdateTypepaymantDto, actorUserId?:number) { this.validateId(id); const fields=this.changedFields(body); if(fields.length===0)throw new BadRequestException('TYPEPAYMENT_UPDATE_REQUIRED'); if(actorUserId===undefined)return this.updateWithManager(this.repository.manager,id,body); if(!this.dataSource)throw new Error('TYPEPAYMENT_TRANSACTION_UNAVAILABLE'); return this.dataSource.transaction((manager)=>this.updateWithManager(manager,id,body,actorUserId)); }
  async reorder(idsValue:unknown,actorUserId?:number){const ids=this.normalizeOrderIds(idsValue);if(!Number.isInteger(actorUserId)||Number(actorUserId)<=0)throw new BadRequestException('TYPEPAYMENT_ACTOR_REQUIRED');if(!this.dataSource)throw new Error('TYPEPAYMENT_TRANSACTION_UNAVAILABLE');return this.dataSource.transaction(async manager=>{const repository=manager.getRepository(TypePayment);const rows=await repository.createQueryBuilder('typePayment').setLock('pessimistic_write').orderBy('typePayment.displayOrder','ASC').addOrderBy('typePayment.id','ASC').getMany();const current=rows.map(row=>row.id);if(ids.length!==current.length||ids.some(id=>!current.includes(id)))throw new BadRequestException('TYPEPAYMENT_REORDER_SCOPE_INVALID');if(ids.every((id,index)=>id===current[index]))return{updated:0,ids};const byId=new Map(rows.map(row=>[row.id,row])),temporaryBase=Math.max(0,...rows.map(row=>Number(row.displayOrder)||0))+rows.length+1;for(let index=0;index<ids.length;index++){const row=byId.get(ids[index]);if(!row)throw new BadRequestException('TYPEPAYMENT_REORDER_SCOPE_INVALID');row.displayOrder=temporaryBase+index;await repository.save(row);}for(let index=0;index<ids.length;index++){const row=byId.get(ids[index]);if(!row)throw new BadRequestException('TYPEPAYMENT_REORDER_SCOPE_INVALID');row.displayOrder=index+1;await repository.save(row);}await this.writeAudit(manager,Number(actorUserId),'typepayment.reordered',rows[0]?.id??ids[0],'Orden de formas de pago actualizado',{before:current,after:ids});return{updated:ids.length,ids};});}
  private normalizeOrderIds(value:unknown){if(!Array.isArray(value)||value.length===0||value.length>500)throw new BadRequestException('TYPEPAYMENT_REORDER_IDS_INVALID');const ids=value.map(Number);if(ids.some(id=>!Number.isInteger(id)||id<=0)||new Set(ids).size!==ids.length)throw new BadRequestException('TYPEPAYMENT_REORDER_IDS_INVALID');return ids;}
  private async createWithManager(manager:EntityManager,input:ReturnType<TypePaymentService['normalizeCreate']>,actorUserId?:number){ const repository=manager.getRepository(TypePayment); await this.ensureUnique(repository,input.code,input.description); const currencies=await this.resolveCurrencies(manager,input.currencyIds,input.defaultCurrencyId); const saved=await repository.save(repository.create({code:input.code,description:input.description,displayOrder:input.displayOrder,annulled:false})); await this.replaceCurrencies(manager,saved.id,currencies,input.defaultCurrencyId); await this.replaceFields(manager,saved.id,input.fields); if(actorUserId!==undefined)await this.writeAudit(manager,actorUserId,'typepayment.created',saved.id,'Tipo de pago creado',{code:saved.code,description:saved.description,currencyIds:input.currencyIds,defaultCurrencyId:input.defaultCurrencyId,fieldCount:input.fields.length}); return this.getWithManager(manager,saved.id); }
  private async updateWithManager(manager:EntityManager,id:number,body:UpdateTypepaymantDto,actorUserId?:number){ const repository=manager.getRepository(TypePayment); const record=await repository.findOne({where:{id}}); if(!record)throw new NotFoundException('TYPEPAYMENT_NOT_FOUND'); const previous={code:record.code,description:record.description,displayOrder:record.displayOrder,annulled:Boolean(record.annulled)}; if(body.code!==undefined)record.code=this.code(body.code); if(body.description!==undefined)record.description=this.text(body.description,'TYPEPAYMENT_DESCRIPTION_REQUIRED'); if(body.displayOrder!==undefined)record.displayOrder=this.order(body.displayOrder); if(body.annulled!==undefined)record.annulled=this.boolean(body.annulled,'TYPEPAYMENT_ANNULLED_INVALID'); await this.ensureUnique(repository,record.code,record.description,id); await repository.save(record); if(body.currencyIds!==undefined||body.defaultCurrencyId!==undefined){const current=await manager.getRepository(PaymentMethodCurrency).find({where:{paymentMethodId:id}});const ids=body.currencyIds??current.map(item=>item.currencyId);const defaultId=body.defaultCurrencyId??current.find(item=>Boolean(item.isDefault))?.currencyId;if(defaultId===undefined)throw new BadRequestException('TYPEPAYMENT_DEFAULT_CURRENCY_REQUIRED');const currencies=await this.resolveCurrencies(manager,ids,defaultId);await this.replaceCurrencies(manager,id,currencies,defaultId);} if(body.fields!==undefined){const fields=this.normalizeFields(body.fields);await this.replaceFields(manager,id,fields);} if(actorUserId!==undefined){const action=body.annulled!==undefined&&previous.annulled!==Boolean(record.annulled)?record.annulled?'typepayment.deactivated':'typepayment.activated':'typepayment.updated';await this.writeAudit(manager,actorUserId,action,id,action==='typepayment.updated'?'Tipo de pago actualizado':record.annulled?'Tipo de pago inactivado':'Tipo de pago activado',{previous,current:{code:record.code,description:record.description,displayOrder:record.displayOrder,annulled:Boolean(record.annulled)}});} return this.getWithManager(manager,id); }
  private async getWithManager(manager:EntityManager,id:number){return manager.getRepository(TypePayment).findOneOrFail({where:{id},relations:{currencies:{currency:true},fields:true}});}
  private async resolveCurrencies(manager:EntityManager,ids:number[],defaultId:number){if(!Array.isArray(ids)||ids.length===0)throw new BadRequestException('TYPEPAYMENT_CURRENCIES_REQUIRED');const unique=[...new Set(ids.map(value=>this.id(value,'TYPEPAYMENT_CURRENCY_INVALID')))];if(!unique.includes(this.id(defaultId,'TYPEPAYMENT_DEFAULT_CURRENCY_INVALID')))throw new BadRequestException('TYPEPAYMENT_DEFAULT_CURRENCY_INVALID');const rows=await manager.getRepository(Currency).find({where:{id:In(unique),isActive:true}});if(rows.length!==unique.length)throw new BadRequestException('TYPEPAYMENT_CURRENCY_NOT_AVAILABLE');return unique;}
  private async replaceCurrencies(manager:EntityManager,paymentMethodId:number,ids:number[],defaultId:number){const repository=manager.getRepository(PaymentMethodCurrency);await repository.delete({paymentMethodId});await repository.save(ids.map((currencyId,index)=>repository.create({paymentMethodId,currencyId,isDefault:currencyId===defaultId,isActive:true,displayOrder:(index+1)*10})));}
  private normalizeFields(value: unknown): Array<PaymentMethodFieldInputDto & { code:string; label:string; fieldType:PaymentFieldType; isRequired:boolean; isActive:boolean }> {
    if (!Array.isArray(value)) throw new BadRequestException('TYPEPAYMENT_FIELDS_ARRAY_REQUIRED');
    if (value.length > 50) throw new BadRequestException('TYPEPAYMENT_FIELDS_COUNT_INVALID');
    const codes = new Set<string>();
    return value.map((raw, index) => {
      if (!raw || typeof raw !== 'object' || Array.isArray(raw)) throw new BadRequestException('TYPEPAYMENT_FIELD_INVALID');
      const field = raw as PaymentMethodFieldInputDto;
      const label = this.fieldText(field.label, 100, 'TYPEPAYMENT_FIELD_LABEL_REQUIRED');
      const code = field.code === undefined || String(field.code).trim() === '' ? this.fieldCode(label, index) : this.fieldCode(String(field.code), index);
      if (codes.has(code)) throw new BadRequestException('TYPEPAYMENT_FIELD_CODE_DUPLICATED');
      codes.add(code);
      const allowed: PaymentFieldType[] = ['text','number','date','phone','reference','select','bank','boolean'];
      if (!allowed.includes(field.fieldType)) throw new BadRequestException('TYPEPAYMENT_FIELD_TYPE_INVALID');
      const minLength = this.nullableLength(field.minLength, 'TYPEPAYMENT_FIELD_MIN_LENGTH_INVALID');
      const maxLength = this.nullableLength(field.maxLength, 'TYPEPAYMENT_FIELD_MAX_LENGTH_INVALID');
      if (minLength !== null && maxLength !== null && minLength > maxLength) throw new BadRequestException('TYPEPAYMENT_FIELD_LENGTH_RANGE_INVALID');
      return { ...field, code, label, fieldType:field.fieldType, isRequired:field.isRequired === undefined ? false : this.boolean(field.isRequired,'TYPEPAYMENT_FIELD_REQUIRED_INVALID'), isActive:field.isActive === undefined ? true : this.boolean(field.isActive,'TYPEPAYMENT_FIELD_STATUS_INVALID'), minLength, maxLength, inputMask:this.nullableText(field.inputMask,100), validationPattern:this.nullableText(field.validationPattern,255), helpText:this.nullableText(field.helpText,255), catalogSource:this.nullableText(field.catalogSource,30) };
    });
  }
  private async replaceFields(manager:EntityManager,paymentMethodId:number,fields:ReturnType<TypePaymentService['normalizeFields']>){const repository=manager.getRepository(PaymentMethodField);await repository.delete({paymentMethodId});if(fields.length===0)return;await repository.save(fields.map((field,index)=>repository.create({paymentMethodId,code:field.code,label:field.label,fieldType:field.fieldType,isRequired:field.isRequired,displayOrder:(index+1)*10,minLength:field.minLength??null,maxLength:field.maxLength??null,inputMask:field.inputMask??null,validationPattern:field.validationPattern??null,helpText:field.helpText??null,catalogSource:field.catalogSource??null,isActive:field.isActive})));}
  private fieldCode(value:string,index:number){const normalized=value.trim().toLowerCase().replace(/[^a-z0-9]+/g,'-').replace(/^-+|-+$/g,'').slice(0,42);const code=normalized||`field-${index+1}`;if(!/^[a-z0-9]+(?:-[a-z0-9]+)*$/.test(code))throw new BadRequestException('TYPEPAYMENT_FIELD_CODE_INVALID');return code;}
  private fieldText(value:unknown,max:number,error:string){if(typeof value!=='string'||value.trim()==='')throw new BadRequestException(error);if(value.trim().length>max)throw new BadRequestException('TYPEPAYMENT_FIELD_TEXT_TOO_LONG');return value.trim();}
  private nullableText(value:unknown,max:number){if(value===undefined||value===null||String(value).trim()==='')return null;const text=String(value).trim();if(text.length>max)throw new BadRequestException('TYPEPAYMENT_FIELD_TEXT_TOO_LONG');return text;}
  private nullableLength(value:unknown,error:string){if(value===undefined||value===null||value==='')return null;const number=Number(value);if(!Number.isInteger(number)||number<0||number>1000)throw new BadRequestException(error);return number;}
  private async ensureUnique(repository:Repository<TypePayment>,code:string,description:string,excludedId?:number){const where=excludedId?{id:Not(excludedId)}:{};const records=await repository.find({where,select:{id:true,code:true,description:true}});if(records.some(row=>row.code.toLowerCase()===code.toLowerCase()))throw new BadRequestException('TYPEPAYMENT_CODE_ALREADY_EXISTS');if(records.some(row=>row.description.trim().toLowerCase()===description.trim().toLowerCase()))throw new BadRequestException('TYPEPAYMENT_DESCRIPTION_ALREADY_EXISTS');}
  private normalizeCreate(body:CreateTypepaymantDto){return{code:this.code(body?.code),description:this.text(body?.description,'TYPEPAYMENT_DESCRIPTION_REQUIRED'),displayOrder:this.order(body?.displayOrder??0),currencyIds:body?.currencyIds,defaultCurrencyId:body?.defaultCurrencyId,fields:this.normalizeFields(body?.fields??[])};}
  private changedFields(body:UpdateTypepaymantDto){if(!body||typeof body!=='object'||Array.isArray(body))return[];return['code','description','displayOrder','annulled','currencyIds','defaultCurrencyId','fields'].filter(field=>Object.prototype.hasOwnProperty.call(body,field));}
  private code(value:unknown){const code=this.text(value,'TYPEPAYMENT_CODE_REQUIRED').toLowerCase();if(!/^[a-z0-9]+(?:-[a-z0-9]+)*$/.test(code)||code.length>50)throw new BadRequestException('TYPEPAYMENT_CODE_INVALID');return code;}
  private text(value:unknown,error:string){if(typeof value!=='string'||value.trim()==='')throw new BadRequestException(error);if(value.trim().length>100)throw new BadRequestException('TYPEPAYMENT_TEXT_TOO_LONG');return value.trim();}
  private order(value:unknown){const order=Number(value);if(!Number.isInteger(order)||order<0)throw new BadRequestException('TYPEPAYMENT_DISPLAY_ORDER_INVALID');return order;}
  private boolean(value:unknown,error:string){if(typeof value!=='boolean')throw new BadRequestException(error);return value;}
  private id(value:unknown,error:string){const id=Number(value);if(!Number.isInteger(id)||id<=0)throw new BadRequestException(error);return id;}
  private validateId(id:number){this.id(id,'TYPEPAYMENT_ID_INVALID');}
  private async writeAudit(manager:EntityManager,actorUserId:number,action:string,entityId:number,summary:string,metadata:Record<string,unknown>){if(!this.audit)throw new Error('SECURITY_AUDIT_SERVICE_UNAVAILABLE');await this.audit.write(manager,{actorUserId,action,entityType:'type_payment',entityId,summary,metadata});}
}
