import { BadRequestException, Injectable, NotFoundException, Optional } from '@nestjs/common';
import { InjectRepository } from '@nestjs/typeorm';
import { DataSource, EntityManager, Repository } from 'typeorm';
import { SecurityAuditService } from '../audit/security-audit.service';
import { ApplicationSettings } from './application-settings.entity';
import { ApplicationSettingsGateway } from './application-settings.gateway';
import { UpdateApplicationSettingsDto } from './dto/update-application-settings.dto';
const FIELDS=['session_timeout_minutes','inactivity_timeout_minutes','countdown_seconds','voucher_format','receipt_format','head_html','body_html','page_html','maximum_rows_report','workshee_format','printer_type','printer_interface'] as const;
@Injectable()
export class ApplicationSettingsService {
  constructor(@InjectRepository(ApplicationSettings) private readonly repository:Repository<ApplicationSettings>,@Optional() private readonly dataSource?:DataSource,@Optional() private readonly audit?:SecurityAuditService,@Optional() private readonly gateway?:ApplicationSettingsGateway){}
  async get(laboratoryId:number){this.id(laboratoryId);const row=await this.repository.findOne({where:{laboratory_id:laboratoryId}});if(!row)throw new NotFoundException('APPLICATION_SETTINGS_NOT_FOUND');return row}
  async getSessionPolicy(laboratoryId:number){const row=await this.get(laboratoryId);return{session_timeout_minutes:row.session_timeout_minutes,inactivity_timeout_minutes:row.inactivity_timeout_minutes,countdown_seconds:row.countdown_seconds}}
  async update(laboratoryId:number,body:UpdateApplicationSettingsDto,actorUserId?:number,excludedSocketId?:string){this.id(laboratoryId);this.validate(body);if(actorUserId===undefined)throw new Error('APPLICATION_SETTINGS_ACTOR_REQUIRED');if(!this.dataSource||!this.audit)throw new Error('APPLICATION_SETTINGS_TRANSACTION_UNAVAILABLE');const saved=await this.dataSource.transaction(async manager=>{const repository=manager.getRepository(ApplicationSettings);const row=await repository.findOne({where:{laboratory_id:laboratoryId}});if(!row)throw new NotFoundException('APPLICATION_SETTINGS_NOT_FOUND');const updated=await repository.save(Object.assign(row,body));await this.writeAudit(manager,actorUserId,updated.id,laboratoryId,Object.keys(body));return updated});this.gateway?.publish({laboratory_id:laboratoryId,session_timeout_minutes:saved.session_timeout_minutes,inactivity_timeout_minutes:saved.inactivity_timeout_minutes,countdown_seconds:saved.countdown_seconds},excludedSocketId);return saved}
  private id(value:number){if(!Number.isInteger(value)||value<=0)throw new BadRequestException('APPLICATION_SETTINGS_ID_INVALID')}
  private validate(body:UpdateApplicationSettingsDto){if(!body||typeof body!=='object'||Array.isArray(body)||Object.keys(body).length===0)throw new BadRequestException('APPLICATION_SETTINGS_UPDATE_REQUIRED');const fields=Object.keys(body);if(fields.some(field=>!FIELDS.includes(field as typeof FIELDS[number])))throw new BadRequestException('APPLICATION_SETTINGS_FIELD_UNKNOWN');for(const field of ['session_timeout_minutes','inactivity_timeout_minutes','countdown_seconds','maximum_rows_report'] as const)if(body[field]!==undefined&&!Number.isInteger(body[field]))throw new BadRequestException('APPLICATION_SETTINGS_INTEGER_INVALID');const session=body.session_timeout_minutes,inactivity=body.inactivity_timeout_minutes,countdown=body.countdown_seconds;if(session!==undefined&&(session<5||session>1440))throw new BadRequestException('APPLICATION_SETTINGS_SESSION_TIMEOUT_INVALID');if(inactivity!==undefined&&(inactivity<1||inactivity>720))throw new BadRequestException('APPLICATION_SETTINGS_INACTIVITY_TIMEOUT_INVALID');if(countdown!==undefined&&(countdown<0||countdown>600))throw new BadRequestException('APPLICATION_SETTINGS_COUNTDOWN_INVALID');const effectiveSession=session??30,effectiveInactivity=inactivity??20,effectiveCountdown=countdown??120;if((effectiveInactivity*60)+effectiveCountdown>effectiveSession*60)throw new BadRequestException('APPLICATION_SETTINGS_TIMEOUT_SUM_INVALID');if(body.maximum_rows_report!==undefined&&(body.maximum_rows_report<1||body.maximum_rows_report>500))throw new BadRequestException('APPLICATION_SETTINGS_ROWS_INVALID');for(const field of ['printer_type','printer_interface'] as const)if(body[field]!==undefined&&(typeof body[field]!=='string'||body[field].length>100))throw new BadRequestException('APPLICATION_SETTINGS_TEXT_INVALID')}
  private async writeAudit(manager:EntityManager,actorUserId:number,entityId:number,laboratoryId:number,changedFields:string[]){await this.audit!.write(manager,{actorUserId,action:'application-settings.updated',entityType:'application_settings',entityId,summary:'Configuracion de la aplicacion actualizada',metadata:{laboratoryId,changedFields}})}
}
