import { PatientAdmissionCloseService } from './patient-admission-close.service';
describe('PatientAdmissionCloseService',()=>{
 const body:any={}; const normalized:any={payments:[{currency:'BASE',amount:10}]}; const resolved:any={exams:[{examCatalogId:1,quantity:1,unitPrice:10,taxRate:0}],payments:[{typePaymentId:1,currency:'BASE',amount:10,description1:'',description2:''}]};
 function setup(){const manager={};const validator={normalize:jest.fn(()=>normalized)};const transaction={execute:jest.fn((work:any)=>work(manager))};const catalogs={resolve:jest.fn(async()=>resolved)};const calculator={calculateExams:jest.fn(()=>[{total:10,subtotal:10,taxTotal:0}]),calculatePayments:jest.fn(()=>[{baseAmount:10}]),summarize:jest.fn(()=>({subtotal:10,taxTotal:0,total:10,paid:10,balance:0}))};const assembler={build:jest.fn(()=>({rows:true}))};const repository={persist:jest.fn(async()=>({admissionId:9}))};const rateResolver={resolve:jest.fn(async()=>({value:1,date:null}))};return{service:new PatientAdmissionCloseService(validator as never,transaction as never,catalogs as never,calculator as never,assembler as never,repository as never,rateResolver as never),manager,validator,transaction,catalogs,calculator,assembler,repository,rateResolver};}
 it('orquesta todas las etapas dentro de una transaccion',async()=>{const value=setup();await expect(value.service.close(body,5)).resolves.toEqual({admissionId:9});expect(value.transaction.execute).toHaveBeenCalledTimes(1);expect(value.catalogs.resolve).toHaveBeenCalledWith(value.manager,normalized);expect(value.repository.persist).toHaveBeenCalledWith(value.manager,{rows:true});});
 it('no persiste si falla catalogos',async()=>{const value=setup();value.catalogs.resolve.mockRejectedValue(new Error('CATALOG_FAIL'));await expect(value.service.close(body,5)).rejects.toThrow('CATALOG_FAIL');expect(value.repository.persist).not.toHaveBeenCalled();});
 it('no persiste si falla calculo',async()=>{const value=setup();value.calculator.summarize.mockImplementation(()=>{throw new Error('BALANCE_FAIL')});await expect(value.service.close(body,5)).rejects.toThrow('BALANCE_FAIL');expect(value.repository.persist).not.toHaveBeenCalled();});
 it('rechaza actor invalido antes de validar',()=>{const value=setup();expect(()=>value.service.close(body,0)).toThrow('PATIENT_ADMISSION_CLOSE_ACTOR_INVALID');expect(value.validator.normalize).not.toHaveBeenCalled();});
 it('solicita tasa autoritativa para pagos locales',async()=>{const value=setup();normalized.payments=[{currency:'LOCAL',amount:10}];await value.service.close(body,5);expect(value.rateResolver.resolve).toHaveBeenCalledWith(value.manager,true);});
});
