import { BadRequestException, Injectable } from '@nestjs/common';
import { AdmissionCalculatedExam, AdmissionCalculatedPayment } from './patient-admission-close-calculator';
import { NormalizedAdmissionClose } from './patient-admission-close.validator';
export interface AdmissionCloseTotals { subtotal:number; taxTotal:number; total:number; paid:number; balance:number; }
@Injectable()
export class PatientAdmissionCloseAssembler {
  build(input:NormalizedAdmissionClose, resolved:any, exams:AdmissionCalculatedExam[], payments:AdmissionCalculatedPayment[], totals:AdmissionCloseTotals, actorUserId:number, now=new Date()) {
    if(!Number.isInteger(actorUserId)||actorUserId<=0)throw new BadRequestException('PATIENT_ADMISSION_CLOSE_ACTOR_INVALID');
    const date=this.isoDate(now), time=this.isoTime(now), rate=this.resolveRate(payments);
    const profile={verification_code:this.optional(input.patient.verificationCode,1),document_number:this.optional(input.patient.documentNumber,10),normalized_document:String(input.patient.documentNumber||'').replace(/\D/g,'')||null,name:String(input.patient.name).trim(),birth_date:input.patient.birthDate||null,sex:Boolean(input.patient.sex),phone:this.optional(input.patient.phone,20),email:this.optional(input.patient.email,100),address:this.optional(input.patient.address,250),source_admission_id:0,identity_review_required:false};
    const admission={patient_profile_id:0,patient_position:0,admission_date:date,admission_time:time,name:profile.name,document_number:profile.document_number||'',verification_code:profile.verification_code||'',age:Number(input.patient.age),month_year:String(input.patient.ageUnit),sex:Boolean(input.patient.sex),birth_date:input.patient.birthDate||date,phone:profile.phone,suggested:this.optional(input.patient.suggested,60)||'',urgent:Boolean(input.patient.urgent),client_id:input.clientId,tariff_id:input.tariffId,process:false,observation:this.optional(input.patient.observation,100),approved:false,canceled:false,foot_payments:null,total:totals.total,total_dollars:totals.total,way_pay_dollars:payments.filter(item=>item.currency==='BASE').reduce((sum,item)=>sum+item.baseAmount,0),total_canceled:totals.paid,subtotal:totals.subtotal,iva:0,tax_base:totals.subtotal,iva_total:totals.taxTotal,discount:0,discount_total:0,dollar_price:rate,dollar_price_date:rate>0?now:null,business_name:resolved.client?.business_name||null,rif:resolved.client?.rif||null,address:resolved.client?.address||null,invoice:null,creditnote:'',invoice_date:null,deliver_date:null,delivery_id:null,receive:null,sample_type:this.optional(input.patient.sampleType,50),sample:String(input.patient.sample),email:profile.email,email_sent:Boolean(input.patient.emailResults),email_status:false,user_id:actorUserId,user_id_canceled:0};
    const examRows=exams.map((item,index)=>{const catalog=resolved.exams.find((row:any)=>row.examCatalogId===item.examCatalogId);return{patientsId:0,exam_catalog_id:item.examCatalogId,description:catalog.description,date:now,group_id:catalog.groupId,position:catalog.position||index+1,amount:item.quantity,price:item.unitPrice,total:item.total,status:false,result:null,size:0,processed_id:null,approved_id:null,tax_description:catalog.taxDescription,tax_amount:item.taxRate,tax_total:item.taxTotal,email_status:0};});
    const wayPay={id_users:actorUserId,id_patients:0,id_client:input.clientId,date:now,date_patients:now,annulment:false};
    const wayPayItems=payments.map(item=>({id_way_pay:0,id_type_payment:item.typePaymentId,currencyId:item.currencyId,enteredAmount:item.enteredAmount,baseAmount:item.baseAmount,localEquivalentAmount:item.localAmount,exchangeRate:rate>0?rate:null,exchangeRateDecimalPlaces:rate>0?this.decimalPlaces(rate):null,exchangeRateDate:rate>0?now:null,fieldValues:[item.description1,item.description2].map((value,index)=>({fieldCode:index===0?'reference_1':'reference_2',fieldLabel:index===0?'Referencia 1':'Referencia 2',fieldType:'text',valueText:value||null,bankId:null})).filter(field=>field.valueText!==null)}));
    return{profile,admission,exams:examRows,wayPay,wayPayItems,audit:{actorUserId,action:'patient-admission.closed',entityType:'patient_admission',entityId:null,summary:'Ingreso de paciente cerrado',metadata:{clientId:input.clientId,tariffId:input.tariffId,examCount:examRows.length,paymentCount:wayPayItems.length,total:totals.total}}};
  }
  private resolveRate(payments:AdmissionCalculatedPayment[]){const row=payments.find(item=>item.baseAmount>0&&item.localAmount>0);return row?Math.round((row.localAmount/row.baseAmount)*100)/100:0;}
  private decimalPlaces(value:number){const text=String(value);return text.includes('.')?text.split('.')[1].length:0;}
  private optional(value:unknown,max:number){if(typeof value!=='string'||value.trim()==='')return null;return value.trim().slice(0,max);}
  private isoDate(value:Date){return value.toISOString().slice(0,10);}
  private isoTime(value:Date){return value.toISOString().slice(11,19);}
}
