import { PatientAdmissionCloseRepository } from './patient-admission-close.repository';
describe('PatientAdmissionCloseRepository',()=>{
 function setup(failAt=''){let id=10;const calls:string[]=[];const repository=(name:string)=>({create:(value:any)=>({...value}),save:jest.fn(async(value:any)=>{calls.push(name);if(failAt===name)throw new Error('PERSIST_FAILURE');if(Array.isArray(value))return value.map(row=>({...row,id:id++}));return{...value,id:value.id??id++};})});const repositories=new Map<any,any>();const manager={getRepository:(entity:any)=>{if(!repositories.has(entity))repositories.set(entity,repository(entity.name));return repositories.get(entity);}} as never;const audit={write:jest.fn(async()=>{calls.push('audit');if(failAt==='audit')throw new Error('PERSIST_FAILURE');})};return{service:new PatientAdmissionCloseRepository(audit as never),manager,calls,audit};}
 const rows=()=>({profile:{name:'Paciente',source_admission_id:0},admission:{patient_profile_id:0,patient_position:1,subtotal:10,iva_total:1.6,total:11.6,total_canceled:11.6},exams:[{patientsId:0}],wayPay:{id_patients:0},wayPayItems:[{id_way_pay:0}],audit:{actorUserId:5,action:'patient-admission.closed',entityType:'patient_admission',entityId:null,summary:'Ingreso cerrado',metadata:{}}});
 it('persiste en orden y asigna todas las llaves',async()=>{const value=setup();const result=await value.service.persist(value.manager,rows());expect(value.calls).toEqual(['PatientProfile','Patient','PatientProfile','Exam','Waypay','Waypayitems','audit']);expect(result).toMatchObject({profileId:10,admissionId:11,wayPayId:13,totals:{total:11.6,paid:11.6}});expect(value.audit.write).toHaveBeenCalledWith(value.manager,expect.objectContaining({entityId:11}));});
 it('propaga falla de examen para rollback exterior',async()=>{const value=setup('Exam');await expect(value.service.persist(value.manager,rows())).rejects.toThrow('PERSIST_FAILURE');expect(value.calls).not.toContain('Waypay');expect(value.audit.write).not.toHaveBeenCalled();});
 it('propaga falla de pago para rollback exterior',async()=>{const value=setup('Waypayitems');await expect(value.service.persist(value.manager,rows())).rejects.toThrow('PERSIST_FAILURE');expect(value.audit.write).not.toHaveBeenCalled();});
 it('propaga falla de auditoria para rollback exterior',async()=>{const value=setup('audit');await expect(value.service.persist(value.manager,rows())).rejects.toThrow('PERSIST_FAILURE');});
});
