import { BadRequestException } from '@nestjs/common';
export interface ValidatedExamFormatGrid { format: Record<string, unknown> | null; size: number; }
const sources=new Set(['text','numeric','formula','autocomplete']),types=new Set(['text','numeric','boolean']),cell=/^[A-Z]{1,3}[1-9][0-9]{0,2}$/;
export function validateExamFormatGrid(v:unknown):ValidatedExamFormatGrid{if(v===null)return{format:null,size:1};if(!rec(v)||v.version!==2||!rec(v.layout)||!rec(v.grid))bad();const d=v.grid.data,c=v.grid.columns,r=v.grid.rows;if(!Array.isArray(d)||d.length<1)bad();if(d.length>100)bad('EXAM_CATALOG_GRID_FORMAT_TOO_LARGE');if(!Array.isArray(c)||c.length!==4||c.some(x=>!integer(x,40,600)))bad();if(!Array.isArray(r)||r.length!==d.length||r.some(x=>!integer(x,16,160)))bad();const data=d.map(row=>{if(!Array.isArray(row)||row.length!==4)bad();return row.map(x=>txt(x,10000))}),merges=merge(v.grid.merges),styles=style(v.grid.styles),fields=field(v.fields),modules=module(v.modules);for(const x of Object.values(fields))if(modules[x.cell])bad();const format={version:2,layout:{logicalWidth:780,heightMode:'content'},grid:{data,columns:c.map(Number),rows:r.map(Number),merges,styles},fields,modules};if(JSON.stringify(format).length>500000)bad('EXAM_CATALOG_GRID_FORMAT_TOO_LARGE');return{format,size:Math.max(1,data.length)}}
function merge(v:unknown){if(v==null)return{};if(!rec(v)||Object.keys(v).length>100)bad();const o:Record<string,[number,number]>={};for(const[k,x]of Object.entries(v)){if(!cell.test(k)||!Array.isArray(x)||x.length!==2||!integer(x[0],1,4)||!integer(x[1],1,100))bad();o[k]=[Number(x[0]),Number(x[1])]}return o}
function style(v:unknown){if(v==null)return{};if(!rec(v)||Object.keys(v).length>400)bad();const o:Record<string,string>={};for(const[k,x]of Object.entries(v)){if(!cell.test(k))bad();o[k]=txt(x,2000)}return o}
function field(v:unknown){if(v==null)return{};if(!rec(v)||Object.keys(v).length>200)bad();const o:Record<string,any>={};for(const[k,x]of Object.entries(v)){if(!/^[a-z][a-z0-9_]{0,79}$/.test(k)||!rec(x)||x.key!==k||!cell.test(String(x.cell))||!sources.has(String(x.source)))bad();const dataType=x.dataType===undefined?(x.source==='numeric'?'numeric':'text'):String(x.dataType),decimals=Number(x.decimals??0),options=Array.isArray(x.options)?x.options.map(y=>req(y,200)):[];if(!types.has(dataType)||!integer(decimals,0,6)||options.length>100||(x.source==='autocomplete'&&options.length===0))bad();o[k]={key:k,label:req(x.label,120),source:String(x.source),formula:txt(x.formula,5000),formulaMode:txt(x.formulaMode??'single',20),selectorFieldKey:txt(x.selectorFieldKey,80),cases:rec(x.cases)?x.cases:{},rules:Array.isArray(x.rules)?x.rules:[],defaultResult:rec(x.defaultResult)?x.defaultResult:{type:'empty',value:''},dataType,decimals,options,cell:String(x.cell)}}return o}
function module(v:unknown){if(v==null)return{};if(!rec(v)||Object.keys(v).length>20)bad();const o:Record<string,{type:'antibiogram';version:1}>={};for(const[k,x]of Object.entries(v)){if(!cell.test(k)||!rec(x)||x.type!=='antibiogram'||x.version!==1)bad();o[k]={type:'antibiogram',version:1}}return o}
function integer(v:unknown,a:number,b:number){const n=Number(v);return Number.isInteger(n)&&n>=a&&n<=b}function req(v:unknown,m:number){if(typeof v!=='string'||v.trim()===''||v.length>m)bad();return v}function txt(v:unknown,m:number){if(v==null)return'';if(typeof v!=='string'||v.length>m)bad();return v}function rec(v:unknown):v is Record<string,any>{return v!==null&&typeof v==='object'&&!Array.isArray(v)}function bad(code='EXAM_CATALOG_GRID_FORMAT_INVALID'):never{throw new BadRequestException(code)}
